name: Run hello.py on schedule

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute (UTC)
  workflow_dispatch:      # Allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run hello.py
        run: python hello.py